default_context:
  add_badges: y
  add_citation_file: y
  create_author_file: y
  project_slug: '{{ cookiecutter.project_name.lower().replace('' '', ''_'').replace(''-'',
    ''_'') }}'
  pypi_username: automl_hannover
  use_github_workflows: y
  use_mypy_typing: y
  use_pydoc_style: y
  use_pypi_deployment_with_travis: y
  use_pytest: y
  use_ruff_format: y
  use_release_helpers: y
