defaults:
  - cluster/local

hydra:
  run:
    dir: results/${method}_${benchmark}/${seed}
  sweep:
    dir: results/${method}_${benchmark}/${seed}
  job:
    chdir: true

method: 1
benchmark: 4
seed: 0
id: 0
