name: Docs

on:
  workflow_dispatch:
  # Trigger on any push to the main
  push:
    branches:
      - main
      - development

  # Trigger on any push to a PR that targets main
  pull_request:
    branches:
      - main
      - development

permissions:
  contents: write

env:
  name: {{ cookiecutter.project_name }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "{{ cookiecutter.python_version }}"

    - name: Install dependencies
      run: |
        pip install ".[dev]"

    - name: Make docs
      run: |
        make clean
        make docs

    - name: Pull latest gh-pages
      if: (contains(github.ref, 'development') || contains(github.ref, 'main'))
      run: |
        cd ..
        {% raw %}git clone https://github.com/${{ github.repository }}.git --branch gh-pages --single-branch gh-pages{% endraw %}

    - name: Copy new docs into gh-pages
      if: (contains(github.ref, 'development') || contains(github.ref, 'main'))
      run: |
        branch_name=${GITHUB_REF##*/}
        cd ../gh-pages
        rm -rf $branch_name
        {% raw %}cp -r ../${{ env.name }}/docs/build/html $branch_name{% endraw %}

    - name: Push to gh-pages
      if: (contains(github.ref, 'development') || contains(github.ref, 'main'))
      run: |
        last_commit=$(git log --pretty=format:"%an: %s")
        cd ../gh-pages
        branch_name=${GITHUB_REF##*/}
        git add $branch_name/
        git config --global user.name 'Github Actions'
        git config --global user.email 'not@mail.com'
        {% raw %}git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}{% endraw %}
        git commit -am "$last_commit"
        git push
