name: Tests

on:
  workflow_dispatch:  # Manually trigger the workflow
  # Triggers with push to main
  push:
    branches:
      - main
      - development

  # Triggers with push to a PR aimed at main
  pull_request:
    branches:
      - main
      - development

env:
  package-name: "{{ cookiecutter.project_name }}"
  test-dir: tests
  extra-requires: "[dev]"  # "" for no extra_requires

  # Arguments used for pytest
  pytest-args: >-
    --durations=20
    -v

jobs:

  # General unit tests
  source-test:
    name: tests

    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash # Default to using bash on all

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: {{ cookiecutter.python_version }}

    - name: Install {% raw %}${{ env.package-name }}{% endraw %}
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        python -m pip install -e {% raw %}".${{ env.extra-requires }}"{% endraw %}

    - name: Store git status
      id: status-before
      shell: bash
      run: |
        echo {% raw %}"::set-output name=BEFORE::$(git status --porcelain -b)"{% endraw %}

    - name: Tests
      run: |
        pytest {% raw %}${{ env.pytest-args }} ${{ env.test-dir }}{% endraw %}

    - name: Check for files left behind by test
      run: |
        {% raw %}before="${{ steps.status-before.outputs.BEFORE }}"{% endraw %}
        after="$(git status --porcelain -b)"
        if [[ "$before" != "$after" ]]; then
            echo "git status from before: $before"
            echo "git status from after: $after"
            echo "Not all generated files have been deleted!"
            exit 1
        fi